name: landing_page
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
  assets:
    - C:/projects/flutter/landing_page/
    - ios/
    - ios/Runner/
    - ios/Runner/Base.lproj/
    - ios/Runner/Assets.xcassets/
    - ios/Runner/Assets.xcassets/AppIcon.appiconset/
    - ios/Runner/Assets.xcassets/LaunchImage.imageset/
    - ios/Flutter/
    - ios/RunnerTests/
    - ios/Runner.xcodeproj/
    - ios/Runner.xcodeproj/xcshareddata/
    - ios/Runner.xcodeproj/xcshareddata/xcschemes/
    - ios/Runner.xcodeproj/project.xcworkspace/
    - ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/
    - ios/Runner.xcworkspace/
    - ios/Runner.xcworkspace/xcshareddata/
    - lib/
    - lib/presentations/
    - web/
    - web/icons/
    - .git/
    - .git/info/
    - .git/logs/
    - .git/logs/refs/
    - .git/logs/refs/heads/
    - .git/logs/refs/remotes/
    - .git/logs/refs/remotes/origin/
    - .git/refs/
    - .git/refs/tags/
    - .git/refs/heads/
    - .git/refs/remotes/
    - .git/refs/remotes/origin/
    - .git/hooks/
    - .git/objects/
    - .git/objects/01/
    - .git/objects/04/
    - .git/objects/06/
    - .git/objects/09/
    - .git/objects/0a/
    - .git/objects/0b/
    - .git/objects/0d/
    - .git/objects/0e/
    - .git/objects/13/
    - .git/objects/14/
    - .git/objects/15/
    - .git/objects/17/
    - .git/objects/18/
    - .git/objects/19/
    - .git/objects/1c/
    - .git/objects/1d/
    - .git/objects/1e/
    - .git/objects/22/
    - .git/objects/25/
    - .git/objects/27/
    - .git/objects/29/
    - .git/objects/2d/
    - .git/objects/2e/
    - .git/objects/2f/
    - .git/objects/30/
    - .git/objects/32/
    - .git/objects/34/
    - .git/objects/36/
    - .git/objects/38/
    - .git/objects/39/
    - .git/objects/3a/
    - .git/objects/3b/
    - .git/objects/3c/
    - .git/objects/3d/
    - .git/objects/3e/
    - .git/objects/41/
    - .git/objects/42/
    - .git/objects/46/
    - .git/objects/47/
    - .git/objects/4c/
    - .git/objects/4d/
    - .git/objects/50/
    - .git/objects/55/
    - .git/objects/58/
    - .git/objects/59/
    - .git/objects/5a/
    - .git/objects/60/
    - .git/objects/61/
    - .git/objects/62/
    - .git/objects/63/
    - .git/objects/64/
    - .git/objects/66/
    - .git/objects/69/
    - .git/objects/6a/
    - .git/objects/6c/
    - .git/objects/6d/
    - .git/objects/6e/
    - .git/objects/72/
    - .git/objects/73/
    - .git/objects/74/
    - .git/objects/76/
    - .git/objects/77/
    - .git/objects/79/
    - .git/objects/7a/
    - .git/objects/7b/
    - .git/objects/7c/
    - .git/objects/7f/
    - .git/objects/80/
    - .git/objects/82/
    - .git/objects/84/
    - .git/objects/85/
    - .git/objects/86/
    - .git/objects/88/
    - .git/objects/89/
    - .git/objects/8a/
    - .git/objects/8b/
    - .git/objects/8d/
    - .git/objects/8e/
    - .git/objects/90/
    - .git/objects/91/
    - .git/objects/93/
    - .git/objects/95/
    - .git/objects/9d/
    - .git/objects/a2/
    - .git/objects/a5/
    - .git/objects/a6/
    - .git/objects/a8/
    - .git/objects/a9/
    - .git/objects/ae/
    - .git/objects/b7/
    - .git/objects/b9/
    - .git/objects/ba/
    - .git/objects/bc/
    - .git/objects/bd/
    - .git/objects/c0/
    - .git/objects/c2/
    - .git/objects/c4/
    - .git/objects/c8/
    - .git/objects/c9/
    - .git/objects/cb/
    - .git/objects/cc/
    - .git/objects/cf/
    - .git/objects/d0/
    - .git/objects/d2/
    - .git/objects/d3/
    - .git/objects/d4/
    - .git/objects/d5/
    - .git/objects/d6/
    - .git/objects/d7/
    - .git/objects/da/
    - .git/objects/db/
    - .git/objects/dc/
    - .git/objects/dd/
    - .git/objects/df/
    - .git/objects/e0/
    - .git/objects/e3/
    - .git/objects/e7/
    - .git/objects/e9/
    - .git/objects/eb/
    - .git/objects/ec/
    - .git/objects/f0/
    - .git/objects/f1/
    - .git/objects/f2/
    - .git/objects/f3/
    - .git/objects/f4/
    - .git/objects/f5/
    - .git/objects/f7/
    - .git/objects/f9/
    - .git/objects/fe/
    - .git/objects/info/
    - .git/objects/pack/
    - test/
    - .idea/
    - .idea/caches/
    - .idea/libraries/
    - .idea/runConfigurations/
    - linux/
    - linux/flutter/
    - macos/
    - macos/Runner/
    - macos/Runner/Configs/
    - macos/Runner/Base.lproj/
    - macos/Runner/Assets.xcassets/
    - macos/Runner/Assets.xcassets/AppIcon.appiconset/
    - macos/Flutter/
    - macos/Flutter/ephemeral/
    - macos/RunnerTests/
    - macos/Runner.xcodeproj/
    - macos/Runner.xcodeproj/xcshareddata/
    - macos/Runner.xcodeproj/xcshareddata/xcschemes/
    - macos/Runner.xcodeproj/project.xcworkspace/
    - macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/
    - macos/Runner.xcworkspace/
    - macos/Runner.xcworkspace/xcshareddata/
    - android/
    - android/app/
    - android/app/src/
    - android/app/src/main/
    - android/app/src/main/res/
    - android/app/src/main/res/values/
    - android/app/src/main/res/drawable/
    - android/app/src/main/res/mipmap-hdpi/
    - android/app/src/main/res/mipmap-mdpi/
    - android/app/src/main/res/drawable-v21/
    - android/app/src/main/res/mipmap-xhdpi/
    - android/app/src/main/res/values-night/
    - android/app/src/main/res/mipmap-xxhdpi/
    - android/app/src/main/res/mipmap-xxxhdpi/
    - android/app/src/main/java/
    - android/app/src/main/java/io/
    - android/app/src/main/java/io/flutter/
    - android/app/src/main/java/io/flutter/plugins/
    - android/app/src/main/kotlin/
    - android/app/src/main/kotlin/com/
    - android/app/src/main/kotlin/com/example/
    - android/app/src/main/kotlin/com/example/landing_page/
    - android/app/src/debug/
    - android/app/src/profile/
    - android/gradle/
    - android/gradle/wrapper/
    - windows/
    - windows/runner/
    - windows/runner/resources/
    - windows/flutter/
    - .dart_tool/
    - .dart_tool/dartpad/

